// Copyright Spike Plugins 2025. All Rights Reserved.

#pragma once

#include "NativeGameplayTags.h"

namespace GameplayUserTags
{
	namespace LayerStack
	{
		GAMEPLAYUSERINTERFACE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(LayerStack_Menu)
		GAMEPLAYUSERINTERFACE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(LayerStack_Game)
		GAMEPLAYUSERINTERFACE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(LayerStack_GameMenu)
		GAMEPLAYUSERINTERFACE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(LayerStack_Modal)
	}

	namespace Screen
	{
		GAMEPLAYUSERINTERFACE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Screen_PressAnyKey)
		GAMEPLAYUSERINTERFACE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Screen_MainMenu)
		GAMEPLAYUSERINTERFACE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Screen_Story)
		GAMEPLAYUSERINTERFACE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Screen_Options)
		GAMEPLAYUSERINTERFACE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Screen_KeyRemap)
	}

	namespace Description
	{
		GAMEPLAYUSERINTERFACE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Description_TestImage)
	}
}
